title: Diamond Formalization
description: Human-friendly guide to the Lean formalization of the diamond-norm transposition paper
url: https://aledo-jun.github.io
baseurl: /diamond
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
